GET http://127.0.0.1:5000/api/students

### GET classes
GET http://127.0.0.1:5000/api/classes

### POST

POST http://127.0.0.1:5000/api/students
Content-Type: application/json

{
    "first_name": "Dapo",
    "last_name": "Sunday",
    "email": "newemail@yahoo.com",
    "username": "Dapsonco92",
    "password": "Dapsonco982",
    "confirm_password": "Dapsonco982",
    "class_id": "Jss 1"
}

### POST 

POST http://127.0.0.1:5000/api/students
Content-Type: application/json

{
    "first_name": "Dap",
    "last_name": "Suy",
    "email": "neweil@yahoo.com",
    "username": "Dapsco92",
    "password": "Donco982",
    "confirm_password": "Donco982",
    "class_id": "Jss 1"
}

### POST 

POST http://127.0.0.1:5000/api/students
Content-Type: application/json

{
    "first_name": "Dapson",
    "last_name": "Suyutar",
    "email": "Manuel122@yahoo.com",
    "username": "Polystar",
    "password": "Drasco109",
    "confirm_password": "Drasco109",
    "class_id": "Jss 1"
}

### GET subject teacher
GET http://127.0.0.1:5000/api/subject_teachers


### DELETE Test
DELETE http://127.0.0.1:5000/api/subject_teachers/294d22ad-b1e6-4f3f-9710-bb864a9c52fb/98754564-2a07-47f4-8362-7a004dab5c29


### GET Classes
POST http://127.0.0.1:5000/api/subject_teachers
Content-Type: application/json

{
    "teacher_id": "294d22ad-b1e6-4f3f-9710-bb864a9c52fb",
    "subject_id": "98754564-2a07-47f4-8362-7a004dab5c29"
}


### GET
GET http://127.0.0.1:5000/api/classes/79b615ad-3305-4fd2-bdc8-7a61986b9ce0


### POST Class
POST http://127.0.0.1:5000/api/classes
Content-Type: application/json


{
    "class_name": "SSS 3"
}

### POST Class
POST http://127.0.0.1:5000/api/classes
Content-Type: application/json


{
    "class_name": "Jss 2"
}

### POST Class
POST http://127.0.0.1:5000/api/classes
Content-Type: application/json


{
    "class_name": "Jss 3"
}


### POST Class
POST http://127.0.0.1:5000/api/classes
Content-Type: application/json

{
    "class_name": "SSS 1"
}

### POST Class
POST http://127.0.0.1:5000/api/classes
Content-Type: application/json

{
    "class_name": "jss1"
}

### POST Class
POST http://127.0.0.1:5000/api/classes
Content-Type: application/json

{
    "class_name": "sss3"
}

### Get classes
GET http://127.0.0.1:5000/api/classes

### DELETE CLASS BY ID
DELETE http://127.0.0.1:5000/api/classes/d5a059e3-5bfa-4fbd-989b-1e90eee53bdd


### 
GET http://127.0.0.1:5000/api/students/095eaadd-4aa2-4efe-8d43-72b860c71995


### PUT Student 79b615ad-3305-4fd2-bdc8-7a61986b9ce0 st_ 
PUT http://127.0.0.1:5000/api/students/095eaadd-4aa2-4efe-8d43-72b860c71995
Content-Type: application/json


{
    "class_id": "79b615ad-3305-4fd2-bdc8-7a61986b9ce0"
}


### POST Teacher
POST http://127.0.0.1:5000/api/teachers
Content-Type: application/json


{
    "first_name": "Femi",
    "last_name": "Useless",
    "email": "femouseless@yahoo.com",
    "username": "femuseless",
    "password": "femcouselessco982",
    "confirm_password": "femcouselessco982"
}

### POST Teacher
POST http://127.0.0.1:5000/api/teachers
Content-Type: application/json


{
    "first_name": "Teacher 2",
    "last_name": "Teacher 2",
    "email": "teacher2@yahoo.com",
    "username": "teacher2",
    "password": "teacher2",
    "confirm_password": "teacher2"
}

### POST Teacher
POST http://127.0.0.1:5000/api/teachers
Content-Type: application/json

{
    "first_name": "Teacher 3",
    "last_name": "Teacher 3",
    "email": "teacher3@yahoo.com",
    "username": "teacher3",
    "password": "teacher3",
    "confirm_password": "teacher3"
}

### POST Teacher
POST http://127.0.0.1:5000/api/teachers
Content-Type: application/json


{
    "first_name": "Teacher 4",
    "last_name": "Teacher 4",
    "email": "teacher4@yahoo.com",
    "username": "teacher4",
    "password": "teacher4",
    "confirm_password": "teacher4"
}

### POST Teacher
POST http://127.0.0.1:5000/api/teachers
Content-Type: application/json

{
    "first_name": "Teacher 5",
    "last_name": "Teacher 5",
    "email": "teacher5@yahoo.com",
    "username": "teacher5",
    "password": "teacher5",
    "confirm_password": "teacher5"
}


### PUT Teacher th_ f9af9976-d524-4dcc-9822-64814ab2c82a
PUT http://127.0.0.1:5000/api/teachers/339de8b5-9778-4bae-9ef1-7cd939680643
Content-Type: application/json

{
    "class_id": "0462182c-1f6c-4537-9222-b9b6498392b6"
}


###
POST http://127.0.0.1:5000/api/teachers/login
Content-Type: application/json

{
    "email": "femouseless@yahoo.com",
    "password": "femcouselessco982"
}

### 
POST http://127.0.0.1:5000/api/students/login
Content-Type: application/json

{
    "email": "newemail@yahoo.com",
    "password": "Dapsonco982"
}

### GET Teacherss
GET http://127.0.0.1:5000/api/teachers


### GET Classes
GET http://127.0.0.1:5000/api/classes



### GET subjects
GET http://127.0.0.1:5000/api/subjects

### POST subjects
POST http://127.0.0.1:5000/api/subjects
Content-Type: application/json

{
    "subject_name": "Physics"
}


### POST subjects
POST http://127.0.0.1:5000/api/subjects
Content-Type: application/json

{
    "subject_name": "Mathematics"
}


### POST subjects
POST http://127.0.0.1:5000/api/subjects
Content-Type: application/json

{
    "subject_name": "English"
}


### POST subjects
POST http://127.0.0.1:5000/api/subjects
Content-Type: application/json

{
    "subject_name": "Agric"
}


### POST subjects
POST http://127.0.0.1:5000/api/subjects
Content-Type: application/json

{
    "subject_name": "Chemistry"
}

### POST subjects
POST http://127.0.0.1:5000/api/subjects
Content-Type: application/json

{
    "subject_name": "Basic Tech"
}

### POST subjects
POST http://127.0.0.1:5000/api/subjects
Content-Type: application/json

{
    "subject_name": "Computer"
}

### POST subjects
POST http://127.0.0.1:5000/api/subjects
Content-Type: application/json

{
    "subject_name": "Business Studies"
}


###
GET http://127.0.0.1:5000/api/admins



###
POST http://127.0.0.1:5000/api/admins
Content-Type: application/json

{
    "first_name": "Admin 1",
    "last_name": "Admin 1",
    "email": "admin1@yahoo.com",
    "username": "admin1",
    "password": "admin1"
}

### POST Teacher
POST http://127.0.0.1:5000/api/teachers
Content-Type: application/json

{
    "first_name": "Teacher 6",
    "last_name": "Teacher 6",
    "email": "teacher6@yahoo.com",
    "username": "teacher6",
    "password": "teacher6",
    "confirm_password": "teacher6",
    "class_id": "SSS 3"
}

### Teacher SS2 -> 294d22ad-b1e6-4f3f-9710-bb864a9c52fb
### Student       "id": "d565af44-2fd6-4ffd-91b4-88102f0c2b86",
### Class ss2       "id": "b7c25f8c-d0c3-4e49-8049-1ab73b99e2a4",

PUT http://127.0.0.1:5000/api/students/d565af44-2fd6-4ffd-91b4-88102f0c2b86
Content-Type: application/json

{
    "class_id": "b7c25f8c-d0c3-4e49-8049-1ab73b99e2a4"
}

### GET Teacher's student
GET http://127.0.0.1:5000/api/teachers/0696771b-0f99-4d17-8ee4-599c6a00cde5/students

### 
GET http://127.0.0.1:5000/api/teachers/0696771b-0f99-4d17-8ee4-599c6a00cde5

### Get teacher 
GET http://127.0.0.1:5000/api/teachers/